# Generated by Django 3.1.7 on 2021-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('1', 'All'), ('2', '7+'), ('3', '12+'), ('4', '15+'), ('5', 'Rated-R'), ('6', '19+')], max_length=1),
        ),
    ]
